yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Главная страница Последние обновления на сайте
    path('', views.index, name='index'),
    # Все посты указанной группы
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    # Создание новой записи
    path('create/', views.post_create, name='post_create'),
    # форма добавления комментариев
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    # Редактирование записи
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    # Django проверяет url-адреса сверху вниз,
    # нам нужно, чтобы Django сначала проверял адреса в приложении users
    path('auth/', include('users.urls', namespace='users')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 


    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    # название группы
    title = models.CharField(
        verbose_name='Название группы',
        help_text='Укажите название новой группы!',
        max_length=200
    )
    # уникальный адрес группы, часть URL
    # (например, для группы любителей котиков
    # slug будет равен cats: group/cats)
    slug = models.SlugField(
        verbose_name='Название группы на латинице',
        help_text=('Значение должно состоять только из букв,'
                   'цифр, знаков подчеркивания или дефиса!'),
        unique=True
    )
    # текст, описывающий сообщество.
    # Этот текст будет отображаться на странице сообщества
    description = models.TextField(
        verbose_name='Краткое описание группы',
        help_text='Укажите описание и направление группы!'
    )

    def __str__(self):
        # выводим название группы
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Поле для Вашего текста в нашей социальной сети!',
        null=False,
        blank=False
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
        help_text='Выберите автора'
    )
    # Ссылка на модель Group
    # Параметр on_delete=models.CASCADE
    # обеспечивает связность данных:
    # если из таблицы User будет удалён пользователь,
    # то будут удалены все связанные с ним посты.
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Укажите группу (необязательно)'
    )

    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
        help_text='Загрузите картинку'
    )
    # Аргумент upload_to указывает директорию,
    # в которую будут загружаться пользовательские файлы.

    def __str__(self) -> str:
        # выводим текст поста
        return self.text[:settings.LEN_OF_POSTS]

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        # Многословное имя во множественном числе
        verbose_name_plural = 'Посты'


class Comment(CreatedModel):

    post = models.ForeignKey('Post',
                             on_delete=models.CASCADE,
                             related_name='comments',
                             verbose_name='Текст поста',
                             blank=True,
                             null=True)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments',
                               verbose_name='Автор')
    text = models.TextField('Текст', help_text='Текст нового комментария')

    class Meta:
        ordering = ('-pub_date',)
        # Многословное имя во множественном числе
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(User, related_name='follower',
                             on_delete=models.CASCADE)
    author = models.ForeignKey(User, related_name='following',
                               on_delete=models.CASCADE)

    class Meta:
        ordering = ('-author',)
        verbose_name = 'Лента автора'
        # Многословное имя во множественном числе
        verbose_name_plural = 'Лента авторов'
        # Ограничения
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'], name='unique_members')]

yatube/posts/forms.py
from django import forms
from django.forms import ModelForm, Select
from .models import Post, Comment


class PostForm(ModelForm):

    def _init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields["group"]

    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        widgets = {"group": Select(attrs={'class': 'form-control',
                                          'id': 'id_group',
                                          'name': 'group'}),
                   "text": Select(attrs={'class': 'form-control',
                                         'required_id': 'id_text',
                                         'name': 'text',
                                         'cols': '40',
                                         'rows': '10'})}
        exclude = ['author']

    def clean_subject(self):
        data = self.changed_data['text']
        if data is None:
            raise forms.ValidationError()
        return data


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from .utils import paginate


def index(request):
    posts = Post.objects.all()
    page_obj = paginate(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginate(request, posts)
    context = {'group': group,
               'posts': posts,
               'page_obj': page_obj}
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    post_count = posts.count()
    page_obj = paginate(request, posts)
    following = (request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author).exists())
    context = {
        'author': author,
        'page_obj': page_obj,
        'post_count': post_count,
        'posts': posts,
        'following': following}

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form = CommentForm()
    post_count = post.author.posts.count()
    context = {
        'post': post,
        'post_count': post_count,
        'form': form,
        'comments': comments}
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    post = None
    if not request.method == 'POST' or not form.is_valid():
        return render(
            request,
            'posts/post_create.html',
            {'form': form, 'post': post})

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if not request.method == 'POST' or not form.is_valid():
        return render(
            request,
            'posts/post_create.html',
            {'form': form, 'post': post})

    post = form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    # Получите пост и сохраните его в переменную post.
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.author = request.user
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    # информация о текущем пользователе доступна в переменной request.user
    posts = Post.objects.filter(author__following__user=request.user)
    page = paginate(request, posts)
    context = {"page_obj": page}
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    user = request.user
    Follow.objects.filter(user=user, author__username=username).delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
          <small for="id_text" class="form-text text-muted">
            {{ form.text.help_text|safe }}
          </small>
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Лента автора{% endblock %}
{% block content %}
  <main> 
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' with follow=True %}    
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      <li>
      {% if post.group %}   
        <!--  все записи группы -->
        <a href="{% url 'posts:group_list' post.group.slug %}">
          {{ post.group }}
        </a> 
      {% endif %}
      </ul>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  </main>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
<main>
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <h3>{{ group.description|linebreaks }}</h3>
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    <!-- под последним постом нет линии -->
  </div>  
</main>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% cache 20 index_page request.user.username %}
  <main> 
    <!-- класс py-5 создает отступы сверху и снизу блока -->
    <div class="container py-5">
      {% include 'posts/includes/switcher.html' with follow=True %}  
      <h1>Последние обновления на сайте</h1>
      {% for post in page_obj %}
        {% include 'posts/includes/post_list.html' %}
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        <li>
          {% if post.group %}   
            <!--  все записи группы -->
            <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group }}
            </a> 
          {% endif %}
        </ul>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      <!-- под последним постом нет линии -->
    </div>  
  </main>
  {% include 'posts/includes/paginator.html' %}
{% endcache %}  
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
  {% if post %}Редактировать запись{% else %}Добавить запись{% endif %}
{% endblock %}
{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if post %}Редактировать запись{% else %}Добавить запись{% endif %}
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger">
                    {% if form.errors %}
                      * Обязательное поле!
                    {% else %}
                      *
                    {% endif %}
                    </span>  
                </label>
                <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                  {{post.text}}
                </textarea>                
                <small id="id_text-help" class="form-text text-muted">
                  {{ form.text.help_text }}
                </small>                  
              </div>            
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Группа
                </label>
                {{form.group}}
                <small id="id_group-help" class="form-text text-muted">
                  {{ form.group.help_text }}
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                {{ form.image}}
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if post %}Сохранить{% else %}Добавить{% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|slice:":30" }}
{% endblock %}
{% block content %}
<main>
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">   
            <!--  все записи группы -->
            <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group }}
            </a> 
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{  post_count  }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      {% if post.author.pk == request.user.pk %}
        <a href="{% url 'posts:post_edit' post.id %}">
          <button type="submit" class="btn btn-primary">
            Редактировать
          </button>
        </a>
      {% endif %}
    </article>
    <article class="col-12 col-md-9">
      {% include 'posts/comments.html' %}
    </article>
  </div>
  
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
<main>
  <div class="container py-5">        
    {% include 'posts/includes/subscribe.html' %}
    {% for post in page_obj %}
      <article>
        {% include 'posts/includes/post_list.html' %}
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      </article>       
      {% if post.group %}   
        <!--  все записи группы -->
        <a href="{% url 'posts:group_list' post.group.slug %}">
          {{ post.group }}
        </a> 
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
</main>
{% endblock %}